# Generated by Django 5.1.6 on 2025-03-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studententry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Student_ID', models.CharField(max_length=15, unique=True)),
                ('Issue', models.TextField()),
                ('Registered_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('year', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], default='1', max_length=1)),
                ('course', models.CharField(choices=[('cs', 'Computer Science'), ('Li', ' Library and Information Technology'), ('se', 'Software Engineering')], default='cs', max_length=2)),
            ],
        ),
    ]
