# Generated by Django 5.1.6 on 2025-03-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='student_nunmber',
            new_name='student_number',
        ),
    ]
