# Generated by Django 5.1.6 on 2025-03-08 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('log_issue', 'Can log an issue'), ('view_issue', 'Can view issues'), ('resolve_issue', 'Can resolve issues'), ('provide_feedback', 'Can provide feedback'), ('assign_issue', 'Can assign issues to lecturers'), ('oversee_issues', 'Can oversee all issues')]},
        ),
        migrations.AlterField(
            model_name='user',
            name='lecturer_reg_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Only alphanumeric characters and hyphens are allowed', regex='^[A-Za-z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Only alphanumeric characters and hyphens are allowed', regex='^[A-Za-z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Only alphanumeric characters and hyphens are allowed', regex='^[A-Za-z0-9-]+$')]),
        ),
    ]
